#!/bin/sh
set -eu

APP_DIR="${STOCK_AGENT_APP_DIR:-/home/aura/internal-tools/apps/stock-agent}"

cd "$APP_DIR"

PYTHON_BIN="${STOCK_AGENT_PYTHON:-/home/aura/.hermes/venv/stock-trading/bin/python}"
if [ ! -x "$PYTHON_BIN" ]; then
  PYTHON_BIN=python3
fi

exec env \
  STOCK_AGENT_MODE="${STOCK_AGENT_MODE:-ai}" \
  STOCK_AGENT_CANDIDATE_LIMIT="${STOCK_AGENT_CANDIDATE_LIMIT:-6}" \
  STOCK_AGENT_LLM_BASE_URL="${STOCK_AGENT_LLM_BASE_URL:-http://192.168.3.213:8911/v1}" \
  STOCK_AGENT_LLM_MODEL="${STOCK_AGENT_LLM_MODEL:-codex-worker}" \
  STOCK_AGENT_LLM_TIMEOUT="${STOCK_AGENT_LLM_TIMEOUT:-120}" \
  STOCK_AGENT_OUTPUT="${STOCK_AGENT_OUTPUT:-/tmp/stock-agent-ai-report.md}" \
  STOCK_AGENT_STATE_PATH="${STOCK_AGENT_STATE_PATH:-/tmp/stock-agent-daily-selection.json}" \
  STOCK_AGENT_HISTORY_PATH="${STOCK_AGENT_HISTORY_PATH:-$APP_DIR/data/recommendation_history.json}" \
  STOCK_AGENT_PERFORMANCE_URL="${STOCK_AGENT_PERFORMANCE_URL:-http://192.168.3.216:8765/performance}" \
  STOCK_AGENT_ENABLE_TICK="${STOCK_AGENT_ENABLE_TICK:-1}" \
  STOCK_AGENT_TICK_LIMIT="${STOCK_AGENT_TICK_LIMIT:-2}" \
  STOCK_AGENT_TRACKING_LIMIT="${STOCK_AGENT_TRACKING_LIMIT:-3}" \
  STOCK_AGENT_SCHEDULE_GUARD="${STOCK_AGENT_SCHEDULE_GUARD:-1}" \
  STOCK_AGENT_PUBLISH_HOURS="${STOCK_AGENT_PUBLISH_HOURS:-9}" \
  STOCK_AGENT_DELIVERY_RUN=1 \
  PYTHONPATH=src \
  "$PYTHON_BIN" src/stock_agent.py
