#!/bin/sh
set -eu

APP_DIR="${STOCK_AGENT_APP_DIR:-/opt/stock-agent}"

cd "$APP_DIR"

PYTHON_BIN="${STOCK_AGENT_PYTHON:-python3}"
if [ ! -x "$PYTHON_BIN" ]; then
  PYTHON_BIN=python3
fi

exec env \
  STOCK_AGENT_MODE="${STOCK_AGENT_MODE:-ai}" \
  STOCK_AGENT_CANDIDATE_LIMIT="${STOCK_AGENT_CANDIDATE_LIMIT:-6}" \
  STOCK_AGENT_LLM_BASE_URL="${STOCK_AGENT_LLM_BASE_URL:-http://127.0.0.1:8911/v1}" \
  STOCK_AGENT_LLM_MODEL="${STOCK_AGENT_LLM_MODEL:-your-model}" \
  STOCK_AGENT_LLM_TIMEOUT="${STOCK_AGENT_LLM_TIMEOUT:-120}" \
  STOCK_AGENT_OUTPUT="${STOCK_AGENT_OUTPUT:-/tmp/stock-agent-ai-report.md}" \
  STOCK_AGENT_ENABLE_TICK="${STOCK_AGENT_ENABLE_TICK:-1}" \
  STOCK_AGENT_TICK_LIMIT="${STOCK_AGENT_TICK_LIMIT:-2}" \
  STOCK_AGENT_DELIVERY_RUN=1 \
  PYTHONPATH=src \
  "$PYTHON_BIN" src/stock_agent.py
